version: '3'
services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.2.3
    platform: linux/amd64
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=X1eOgHGeik5sTDk8Y04XZ1MuNLQgJIDyOIN2f8CcQlg=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_webserver_secret_key
    volumes:
      - ./../../dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.2.3
    platform: linux/amd64
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=X1eOgHGeik5sTDk8Y04XZ1MuNLQgJIDyOIN2f8CcQlg=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_webserver_secret_key
    volumes:
      - ./../../dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    command: scheduler

  airflow-init:
    image: apache/airflow:2.2.3
    platform: linux/amd64
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=X1eOgHGeik5sTDk8Y04XZ1MuNLQgJIDyOIN2f8CcQlg=
    depends_on:
      - postgres
    command: db init

volumes:
  postgres_data:
  logs:
  plugins:
