version: '3'
services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    platform: linux/amd64
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=9ugH_Fxt8pAx3ztwftJCqn4ICgfgckLW-EBu1xlpZYI=
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_webserver_secret_key_here
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: bash -c "/entrypoint.sh && airflow webserver"

  airflow-scheduler:
    build: .
    platform: linux/amd64
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=9ugH_Fxt8pAx3ztwftJCqn4ICgfgckLW-EBu1xlpZYI=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    command: bash -c "/entrypoint.sh && airflow scheduler"

volumes:
  postgres_data:
  logs:
  plugins:
